name: jobDetective Creation DEVELOPMENT BRANCH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
     branches: [ development ]


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    ##############TEST CREATION SUCCESS##################

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: jobdetective
        IMAGE_TAG: dev
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}



#####notes####
# GHA ECR setup
#https://github.com/marketplace/actions/push-to-amazon-ecr
#https://github.com/aws-actions/amazon-ecr-login <- i used this